# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name:  Install
      run:   |
            if [ "$RUNNER_OS" == "Linux" ]; then
              sudo apt-get install -y stalonetray libgtk2.0-0
            elif [ "$RUNNER_OS" == "Windows" ]; then
              choco install important_windows_software
            else
              echo "$RUNNER_OS not supported"
              exit 1
            fi
      shell: bash
    - name: Checkout misc repo
      uses: actions/checkout@v2
      with:
        repository: jjYBdx4IL/misc
        path: co.misc
#    - name: Checkout aspectj-utils repo
#      uses: actions/checkout@v2
#      with:
#        repository: jjYBdx4IL/aspectj-utils
#        path: co.aspectj-utils
    - name: Build misc dependency with Maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -V -B install -f co.misc -DskipTests -DskipITs -Ddependency-check.skip -Dmaven.javadoc.skip
#    - name: Build aspectj-utils dependency with Maven
#      uses: GabrielBB/xvfb-action@v1
#      with:
#        run: mvn -B install -f co.aspectj-utils -DskipTests -DskipITs -Ddependency-check.skip -Dmaven.javadoc.skip
    - name: Build with Maven
      uses: GabrielBB/xvfb-action@v1
      with:
        run: mvn -B install 
